### ISSUE TITLE
ImportError: cannot import name _postprocess_conv2d_output

### ISSUE THREAD

**Issue by zccoder** [titu1994/DenseNet#33]
The enviroment that I run was:
tensoflow-gpu 1.4.0
keras 2.0.9

The problem occurred while I ran `python cifar10.py`:
```
Traceback (most recent call last):
  File "densenet.py", line 28, in <module>
    from subpixel import SubPixelUpscaling
  File "/home1/zhucheng/contest/ChallengeAI/ai_challenger_scene_train_20170904/DenseNet/subpixel.py", line 11, in <module>
    import tensorflow_backend as K_BACKEND
  File "/home1/zhucheng/contest/ChallengeAI/ai_challenger_scene_train_20170904/DenseNet/tensorflow_backend.py", line 6, in <module>
    from keras.backend.tensorflow_backend import _postprocess_conv2d_output
ImportError: cannot import name _postprocess_conv2d_output

```
I am sure that I had installed the env well. Any advice for this? I am new to keras and tf.

**Comment by zccoder** [comment]
I find the answer. It is just the difference of keras. I used keras by fchollet. However this project is using farizrahman4u/keras-contrib. At last, I just go to this url:
```
https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/backend/tensorflow_backend.py
```
And copy _postprocess_conv2d_output and _preprocess_conv2d_input on my own. That is OK now!

**Comment by titu1994** [comment]
Sorry for the delay. Got caught up in midsems. This should be fixed properly now for the Tensorflow backend

**Comment by Chunluting** [comment]
The enviroment that I run was:
tensoflow 1.10.0
keras 2.2.2

The problem occurred while I ran python train_coco.py:

Traceback (most recent call last):
  File "train_coco.py", line 15, in <module>
    from models import *
  File "/home/chun/src/Keras-FCN/models.py", line 6, in <module>
    from keras_contrib.applications import densenet
  File "/home/chun/CHUN/anaconda3/envs/KFCN/lib/python3.6/site-packages/keras_contrib-1.2.1-py3.6.egg/keras_contrib/__init__.py", line 2, in <module>
  File "/home/chun/CHUN/anaconda3/envs/KFCN/lib/python3.6/site-packages/keras_contrib-1.2.1-py3.6.egg/keras_contrib/backend/__init__.py", line 14, in <module>
  File "/home/chun/CHUN/anaconda3/envs/KFCN/lib/python3.6/site-packages/keras_contrib-1.2.1-py3.6.egg/keras_contrib/backend/tensorflow_backend.py", line 10, in <module>
ImportError: cannot import name '_postprocess_conv3d_output'
